### ISSUE TITLE
Add option for whitelisting specific packages

### ISSUE THREAD

**Issue by dvaeversted** [dominikb/composer-license-checker#17]
It would be great if there was an option on the `check` command, where you could whitelist one or more specific packages.

My use case is that we have some internal packages marked as "proprietary" license, while i could allow this, it would also allow introducing other packages with this license which we do not want.
Adding an option to instead whitelist a few specific packages, would make it possible to solve this.

**Comment by dominikb** [comment]
Hi @dvaeversted 

thanks for opening this issue.

Off the top of my head I would think of something like this:
```sh
./composer-licence-checker check --allowlist MIT \
        --allow dominkb/composer-licence-checker \ # Skips any checks for this package, not regarding versions
        --allow dominikb  # Skips checks for any packages of this author
```
The __--allow__ flag can be used multiple times and those would overwrite all deny- or allowlist checks for the given package.

Would this fit your needs?

**Comment by dvaeversted** [comment]
That would work perfectly, nice touch with both being able to allow a specific package aswell as an author in whole :+1:

**Comment by dominikb** [comment]
Just released a version __2.2.0__ which includes this feature.

Either run `composer update` or change the minimum version by running `composer require dominikb/composer-license-checker:^2.2`
