### ISSUE TITLE
Display packages per license in report command

### ISSUE THREAD

**Issue by dominikb** [dominikb/composer-license-checker#21]
Add an option to the `report` command that enables a more verbose output and shows all packages for each license. This could also take into account the `--verbose` settings.

Given there can be quite a lot of installed packages per project, it should also be possible to filter for specific licenses. Grouping reported packages by the author(s) could also be a nice-to-have feature.

````
# Example usage

$ composer-license-checker report --show-packages

Count 1 - MIT (https://tldrlegal.com/license/mit-license)
+----------------+-------------+-------------------+
| CAN            | CAN NOT     | MUST              |
+----------------+-------------+-------------------+
| Commercial Use | Hold Liable | Include Copyright |
| Modify         |             | Include License   |
| Distribute     |             |                   |
| Sublicense     |             |                   |
| Private Use    |             |                   |
+----------------+-------------+-------------------+

dominikb/composer-license-checker (2.3.0)

$ composer-license-checker report --show-packages --grouped

dominikb
packages: composer-license-checker, composer-license-checker2, some-other-package
````

**Comment by medixcare** [comment]
Version 2.4 which is the latest on packagist does not contain code to allow those params.
Would it be possible to publish an updated version?

**Comment by dominikb** [comment]
> Version 2.4 which is the latest on packagist does not contain code to allow those params. Would it be possible to publish an updated version?

Thanks for pointing this out. I've unintentionally tagged the wrong commit it seems. 

I've now moved the tag to the correct commit and running `composer update` should automatically update to the correct version now.
