### ISSUE TITLE
License details is not displayed

### ISSUE THREAD

**Issue by nsrosenqvist** [dominikb/composer-license-checker#26]
It seems like maybe the integration with tldrlegal.com is broken in the latest version. This is what I get when I run a report:
<img width="562" alt="Screenshot 2023-08-07 at 11 04 21" src="https://github.com/dominikb/composer-license-checker/assets/1303475/db6c7232-0986-4475-9596-61ddb5e79954">

**Comment by dominikb** [comment]
Hi, thanks for reporting it.

It seems that tldrlegal reworked their website and the crawler did not work anymore. I've released a new version that includes a fix for this.
